/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_wooga_uvm_UnityVersionManager */

#ifndef _Included_net_wooga_uvm_UnityVersionManager
#define _Included_net_wooga_uvm_UnityVersionManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_wooga_uvm_UnityVersionManager
 * Method:    uvmVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_wooga_uvm_UnityVersionManager_uvmVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
